### ISSUE TITLE
Start development of a GUI by forking GameConqueror

### ISSUE THREAD

**Issue by sriemer** [ugtrain/ugtrain#34]
@Mortezaipo will help creating a GUI for ugtrain. It will be called "ugtrain-gui".

In the first stage all it needs to do is the stuff GameConqueror does with the only exception that it **may not use root privileges**. It must run the game itself as the child of scanmem instead. The good news is that ugtrain can run scanmem and the game exactly like that. It is the `ugtrain -S <config>` command.

So the tasks are:
- create a scanmem fork and put it to ugtrain/scanmem on GitHub
- integrate the scanmem source as a git sub-module to the directory "scanmem" in the top level directory
- copy over the GameConqueror source from scanmem/gui to src/gui
- drop Python 2 support by adjusting shebang lines to Python 3
- rename GameConqueror to ugtrain-gui and replace the GameConqueror logo with the ugtrain logo
- mark that ugtrain-gui is a GameConqueror fork
- remove the game process selector
- create a dialogue to run the game together with scanmem
- use the command `ugtrain -S <config>`
- use the ugtrain config commands ProcessName, game_call, game_path and game_params
- ignore all other ugtrain config entries which could be there and don't remove them when saving a config
- create dialogues for loading and saving ugtrain config files
- automatically save the config if running the game from the game start dialogue if something changed
- ask for the config location to save it in case no path has been given yet
- still use the cheat list of GC for now to lock/freeze found values - don't put these to the ugtrain config for now
- only use the libscanmem interfaces on the backend side for now

The result of the first development stage is just a GameConqueror which doesn't require root privileges.

**Comment by Mortezaipo** [comment]
Dear Sebastian,
Designing Ugtrain-GUI is under construction, I'm involved in reading Ugtrain main document.

**Comment by sriemer** [comment]
Thanks, now that v0.3 is released I will do the required preparations soon.

**Comment by Alkaris** [comment]
I have to ask why you wouldn't want ugtrain to use root at all, because you do seem to be using scanmem, and it doesn't work well without root. It would severely limit ugtrain to do the things that scanmem allows you to do when scanning for address values. I know it's probably not the most ideal thing running it as root, but I just don't think it will work well without, especially if you want to do deeper searches for address values which aren't so easily found.

scanmem even tells you when simply run from the CLI
```
$ scanmem
error: *** YOU ARE NOT RUNNING scanmem AS ROOT, IT MAY NOT WORK WELL. ***
```

the manpage for scanmem also explains


> scanmem is an interactive debugging utility that can be used to isolate the address of a variable in an
>        executing process by successively scanning the process' address space looking for matching  values.  By
>        informing scanmem how the value of the variable changes over time, it can determine the actual location
>        (or locations) of the variable by successively eliminating non-matches.  scanmem  determines  where  to
>        look  by  searching  for mappings with read / write permission, these are referred to as regions. Users
>        can eliminate regions they believe are likely unrelated to the target variable (for example, located in
>        a shared library unrelated to the variable in question), this will improve the speed of the scan, which
>        can initially be quite slow in large programs.
> 

furthermore details in the manpage

> ATTENTION: scanmem usually requires root privileges. See BUGS for details.

and explains as so

> scanmem usually requires root privileges for ptrace(2) because security modules control ptrace()  capabilities. On x86 and x86_64 there is usually the Yama security module providing the file /proc/sys/kernel/yama/ptrace_scope.  It is available since Linux 3.4. If this file contains "1", then  only  parents may  ptrace()  their  children  without  root privileges. This means that scanmem would have to run the game. This is not possible as this would require major design changes. So we run scanmem as root.

**Comment by sriemer** [comment]
[unrelated comment deleted and answered via e-mail]

**Comment by Alkaris** [comment]
Well if you were the maintainer of scanmem and GameConqueror, you sure
didn't do a very good job coding it in a way so it didn't have to work like
that if you had to start another project that's a fork of the previous code
works. and just a little FYI, anyone can post to GitHub issues to discuss
things that people are working on, discussions of project issues as well as
general question things that relate to the code projects, if you didn't
want people posting then maybe you should of set it to contributors and
maintainers only who can post.

as for your explanation of the security modules and how they differ from
Ubuntu vs OpenSUSE, you didn't think to document to explain these parts in
the manpage as well? I find it pretty common for code devs to neglect
certain things from their documentations because some things may not seem
relevant for documenting, but could be important piece of information to
know.

**Comment by sriemer** [comment]
I don't need a GUI, I don't have the time to develop a GUI or to implement ugtrain support into GameConqueror. Even more successful projects have the same curse - single maintainer has to develop everything by himself. So I'll close this.

I realize it: ugtrain is my personal game cheating research project and I should treat it like that.
